
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div style="width: 100%; padding:20px; text-align:center; box-sizing:border-box; background:url(https://www.automotohr.com//assets/images/bg-body.jpg); opacity:0.9;  top:0; left:0;"><img src="https://www.automotohr.com//assets/images/email-new-logo.png"></div>
            <?php echo $invoice; ?>
            <table cellspacing="0" cellpadding="10" border="0" width="100%" background="https://www.automotohr.com//assets/images/bg-body.jpg"><thead><th style="text-align:center !important; color: #000; padding:10px 0;" colspan="2"><strong style="font-size:16px;">CONTACT ONE OF OUR TALENT NETWORK PARTNERS AT</strong></th></thead><tbody><tr><td><div style="text-align:center !important; color: #000;"><div style="color: #00a700; margin:0 0 15px 0; font-size:16px;"><strong>Sales Support</strong></div><div style="margin:0 0 10px 0;"><a style="color:#000; text-decoration:none;" href="tel:+888-871-3096 ext 1"><img src="https://www.automotohr.com//assets/images/phone-icon.png">&nbsp;&nbsp;<strong>(888) 794-0794 ext 1</strong></a></div></div><div style="text-align:center !important; color: #000;"><span style=" font-weight:600;"><img src="https://www.automotohr.com//assets/images/email-icon.png">&nbsp;&nbsp;Accounts@AutomotoHR.com</span></div></td><td><div style="text-align:center !important; color: #000;"><div style="color: #00a700; margin:0 0 15px 0; font-size:16px;"><strong>Technical Support</strong></div><div style="margin:0 0 10px 0;"><a style="color:#000; text-decoration:none;" href="tel:+888-871-3096 ext 2"><strong><img src="https://www.automotohr.com//assets/images/phone-icon.png">&nbsp;&nbsp;(888) 794-0794 ext 2</strong></a></div></div><div style="text-align:center !important; color: #000;"><span style=" font-weight:600;"><img src="https://www.automotohr.com//assets/images/email-icon.png">&nbsp;&nbsp;Support@AutomotoHR.com</span><p>&nbsp;</p></div></td></tr></tbody></table>
        </div>
    </div>
</div>
