<div class="main-content">
    <div class="container">
        <div class="row">					
            <div class="col-md-12">
                <!-- Page Title Start -->
                <header class="heading-title">
                    <h2 class="page-title">Privacy Policy</h2>
                </header>
                <!-- Page Title End -->
                <!-- AMR Separator Start -->
                <div class="arm-separator">
                    <span><i class="fa fa-angle-down"></i></span>
                </div>
                <!-- AMR Separator End -->
                <!-- ARM Privacy Policy Start -->
                <div class="amr-privacy-policy">
                    <h2>Last Revised: Jan 12, 2017</h2>
                    <p>For <?php echo STORE_NAME; ?>, protecting your private information is our priority. We have prepared this Privacy Policy to describe to you our practices regarding the Personal Information (as defined below) we collect from users of our website, located at www.<?php echo ucwords(STORE_DOMAIN); ?>, our mobile application (“Application(s)”), and our widgets (collectively, the “Site”) and all other online services of <?php echo STORE_NAME; ?> Inc. (“Services”). For the purposes of this Privacy Policy, unless otherwise noted, all references to <?php echo STORE_NAME; ?> include www.<?php echo ucwords(STORE_DOMAIN); ?> and <?php echo STORE_NAME; ?> Inc.</p>
                    <p>We respect each individual’s right to personal privacy. We will collect and use information we receive directly from you through our web site only in the ways disclosed in this Privacy Policy. Information provided to <?php echo STORE_NAME; ?> by our corporate customers is collected by those customers under their own privacy policies. This policy does not apply to practices that <?php echo STORE_NAME; ?> does not own or control, or to individuals that <?php echo STORE_NAME; ?> does not employ or manage. By using www.<?php echo ucwords(STORE_DOMAIN); ?>, you agree to the data practices described in this statement and you expressly consent to the collection, use and disclosure of your Personal Information in accordance with this Privacy Policy.</p>
                    <p><?php echo STORE_NAME; ?> adheres to the set of data protection principles developed by the United States Department of Commerce, in collaboration with the European Commission and the Federal Data Protection and Information Commissioner of Switzerland, which produced the U.S.-European Union Safe Harbor Framework Documents and U.S.-Swiss Safe Harbor Framework Documents. The privacy principles in this policy are based on these Safe Harbor Principles and are further articulated in the <?php echo STORE_NAME; ?> Safe Harbor Privacy Policy (“Safe Harbor Policy”) available at <?php echo STORE_FULL_URL_SSL; ?>/safe-harbor/ that sets out the privacy principles to which <?php echo STORE_NAME; ?> adheres, including as it relates to personal information transferred from the European Union (“EU”) and/or Switzerland to the United States (“U.S.”).</p>
                    <p>This published Privacy Policy and the Safe Harbor Policy are accurate, comprehensive, prominently displayed, completely implemented, accessible and conform to the Safe Harbor Principles. In addition, we provide appropriate employee training (and discipline) and have internal procedures for periodically conducting objective reviews of our compliance with the Safe Harbor Principles. A statement verifying the self-assessment is signed by a corporate officer or other authorized representative of the organization annually.</p>
                    <p class="text-title">Collection of your Personal Information</p>
                    <p><?php echo STORE_NAME; ?> may collect Personal Information, such as your name and other personal and non-personal information. If you purchase products and services through www.<?php echo ucwords(STORE_DOMAIN); ?>, we may request billing and credit card information. This information is not stored.</p>
                    <p>Information about your computer hardware and software may be automatically collected by <?php echo STORE_NAME; ?>. This information can include: your IP address, browser type, domain names, access times and referring website addresses. This information is used for the operation of the service, to maintain and the improve quality of the service, and to provide general statistics regarding use of www.<?php echo ucwords(STORE_DOMAIN); ?>.</p>
                    <p><?php echo STORE_NAME; ?> encourages you to review the privacy statements of websites to which you choose to link from www.<?php echo ucwords(STORE_DOMAIN); ?> so that you can understand how those websites collect, use and share your information. <?php echo STORE_NAME; ?> is not responsible for the privacy statements or other content on websites outside of www.<?php echo ucwords(STORE_DOMAIN); ?>.</p>
                    <p class="text-title">Use of your Personal Information</p>
                    <p><?php echo STORE_NAME; ?> collects and uses your Personal Information to operate its website and deliver the services you have requested.</p>
                    <p><?php echo STORE_NAME; ?> may also use your Personal Information to inform you of other products, services or job opportunities available from and through <?php echo STORE_NAME; ?>. <?php echo STORE_NAME; ?> may also contact you via surveys to conduct research about your opinion of current services or of potential new services that may be offered.
                    </p>
                    <p><?php echo STORE_NAME; ?> does not sell, rent or lease its customer lists to third parties.</p>
                    <p><?php echo STORE_NAME; ?> may share usage data with trusted partners to help perform usage statistical analysis or provide customer support. All such third parties are prohibited from using your Personal Information except to provide these services to <?php echo STORE_NAME; ?>, and they are required to maintain the confidentiality of your information.</p>
                    <p><?php echo STORE_NAME; ?> may keep track of the websites and pages our users visit within <?php echo STORE_NAME; ?>, in order to improve your user experience and determine what <?php echo STORE_NAME; ?> services are the most popular.</p>
                    <p><?php echo STORE_NAME; ?> will disclose your Personal Information, without notice, only if required to do so by law or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on <?php echo STORE_NAME; ?> or the site; (b) protect and defend the rights or property of <?php echo STORE_NAME; ?>; and, (c) act under exigent circumstances to protect the personal safety of users of <?php echo STORE_NAME; ?>, or the public.</p>
                    <p class="text-title">Use of Cookies</p>
                    <p>www.<?php echo STORE_NAME; ?>.com may use “cookies” to help you personalize your online experience. A cookie is a text file that is placed on your hard disk by a web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you.</p>
                    <p>One of the primary purposes of cookies is to provide a convenience feature to save you time. The purpose of a cookie is to tell the Web server that you have returned to a specific page. For example, if you personalize <?php echo STORE_NAME; ?> pages, or register with <?php echo STORE_NAME; ?> site or services, a cookie helps <?php echo STORE_NAME; ?> to recall your specific information on subsequent visits. This simplifies the process of recording your Personal Information, such as Login information. When you return to www.<?php echo ucwords(STORE_DOMAIN); ?>, the information you previously provided can be retrieved, so you can easily use the <?php echo STORE_NAME; ?> features that you customized.</p>
                    <p>You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the <?php echo STORE_NAME; ?> services or websites you visit.</p>
                    <p class="text-title">Security of your Personal Information</p>
                    <p><?php echo STORE_NAME; ?> uses industry-standard technologies when transferring and receiving consumer data exchanged between <?php echo STORE_NAME; ?> and third parties to help ensure its security. <?php echo STORE_NAME; ?>’ website has security measures in place to protect the loss, misuse and alteration of information.</p>
                    <p>User data may be stored on servers maintained by Amazon Web Services and subject to their security safeguards.</p>
                    <p>All financial transactions are made securely through PayPal.</p>
                    <p class="text-title">Children Under Thirteen</p>
                    <p><?php echo STORE_NAME; ?> does not knowingly collect Personal Information from children under the age of thirteen. If you are under the age of thirteen, you must ask your parent or guardian for permission to use www.<?php echo ucwords(STORE_DOMAIN); ?>. If a child under 13 submits Personal Information to Company and we learn that the Personal Information is the information of a child under 13, we will attempt to delete the information as soon as possible. If you believe that we might have any Personal Information from a child under 13, please contact us at 951-385-8204 or contact@<?php echo ucwords(STORE_DOMAIN); ?>.</p>
                    <p class="text-title">Disconnecting your <?php echo STORE_NAME; ?> Account from Third Party Websites</p>
                    <p>You will be able to connect your <?php echo STORE_NAME; ?> account to third party accounts. BY CONNECTING YOUR <?php echo STORE_NAME; ?> ACCOUNT TO YOUR THIRD PARTY ACCOUNT, YOU ACKNOWLEDGE AND AGREE THAT YOU ARE CONSENTING TO THE CONTINUOUS RELEASE OF INFORMATION ABOUT YOU TO OTHERS (IN ACCORDANCE WITH YOUR PRIVACY SETTINGS ON THOSE THIRD PARTY SITES). IF YOU DO NOT WANT INFORMATION ABOUT YOU, INCLUDING PERSONALLY IDENTIFYING INFORMATION, TO BE SHARED INTHIS MANNER, DO NOT USE THE THIS FEATURE. You may disconnect your account from a third party account at any time. Users may disconnect their accounts from third-party websites by visiting their “Account Settings” page.</p>
                    <p class="text-title">International Users</p>
                    <p>Please note that the personal information you submit to us may be transferred to the United States and other countries to be processed by us in order to provide this Site to you or for such other purposes as set forth in this Policy and the Safe Harbor Policy. If you are not a resident of the United States, you consent and agree that we may collect, process, use, and store your personal information, as discussed in this Policy and the Safe Harbor Policy, outside your resident jurisdiction, including in the United States. Please be aware that United States law and laws of other countries where we may store and process your data may offer different levels of protection for personal information than may be available in your country.</p>
                    <p><?php echo STORE_NAME; ?> has certified that it adheres to the Safe Harbor Privacy Principles of notice, choice, onward transfer, security, data integrity, access, and enforcement. To learn more about the Safe Harbor program, and to view the status of <?php echo STORE_NAME; ?>’s certification, please visit http://www.export.gov/safeharbor/.</p>
                    <p class="text-title">Changes to this Statement</p>
                    <p><?php echo STORE_NAME; ?> will occasionally update this Statement of Privacy to reflect company and customer feedback. <?php echo STORE_NAME; ?> encourages you to periodically review this Statement to be informed of how <?php echo STORE_NAME; ?> is protecting your information.</p>
                </div>
                <!-- ARM Privacy Policy End -->                
            </div>
        </div>
    </div>
    <?php if (!$this->session->userdata('logged_in') && $title != 'Register') { ?> 
        <?php $this->load->view('main/demobuttons'); ?>
    <?php } ?> 
</div>