<div style="font-size:18px;">These Payroll Service Terms (these “Payroll Terms”), together with the AutomotoHR Terms of Service Agreement available at <a href="https://revamp.automotohr.com/automotohr-payroll-service-terms" target="_blank" style="color: rgb(11, 118, 210);">www.AutomotoHR.com/terms-of-service</a> (the “AutomotoHR Terms”) (collectively, the “Payroll Agreement”), set forth the terms and conditions under which AutomotoSocial llc, Inc., a Delaware corporation doing business as AutomotoHR (“AutomotoHR”), agrees to provide to User certain payroll services and other related services (the “Payroll Service”), which are provided through AutomotoHR’s website, <a href="https://automotoHR.com" target="_blank" style="color: rgb(11, 118, 210);">www.AutomotoHR.com.</a></div>

<br>

<div style="font-size:18px;">These Payroll Terms are “Service Terms” under the AutomotoHR Terms. Capitalized terms used but not otherwise defined in these Payroll Terms shall have the meanings ascribed to such terms in the AutomotoHR Terms. The Payroll Agreement is a legally binding agreement between User and AutomotoHR. User is encouraged to read the Payroll Agreement carefully and to save a copy of it for User’s records. If User is agreeing to these Payroll Terms on behalf of a business or an individual other than User, User represents and warrants that User has authority to bind that business or other individual to the Payroll Agreement, and User’s agreement to these terms will be treated as the agreement of such business or individual. In that event, “User” (as defined in the AutomotoHR Terms) also refers to that business or individual. By (i) clicking the applicable button to indicate User’s Service Plan choice, (ii) clicking the applicable button to indicate User’s acceptance of the Payroll Agreement, or (iii) accessing or using the Payroll Service, User accepts the Payroll Agreement, and User agrees, effective as of the date of such action, to be bound by the Payroll Agreement.</div>
<br>
<br>

<div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
        <p><strong>1.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">These Payroll Terms Are Part of and Are Governed by the AutomotoHR Terms</span>. 
        The terms and conditions of the AutomotoHR Terms agreed to in connection with the creation of User’s Account, including but not limited to all representations, warranties, covenants, disclaimers, limitations on liability, agreements, and indemnities relating to the Services, are incorporated herein by reference, and User acknowledges and agrees that the representations, warranties, covenants, disclaimers, limitations on liability, agreements, and indemnities contained in the AutomotoHR Terms shall remain in full force and effect to the full extent provided therein.
    </p>
        <p>If the terms and conditions of these Payroll Terms conflict with the terms and conditions of the AutomotoHR Terms, the terms and conditions of these Payroll Terms shall control with respect to the provision of the Payroll Service.</p>
        <p> 
        THE AUTOMOTOHR TERMS, AVAILABLE AT <a href="https://revamp.automotohr.com/terms-of-service" target="_blank" style="color: rgb(11, 118, 210);">WWW.AUTOMOTOHR.COM/TERMS-OF-SERVICE</a>, CONTAIN IMPORTANT INFORMATION REGARDING LIMITATIONS OF AUTOMOTOHR’S LIABILITY, AUTOMOTOHR’S WARRANTY DISCLAIMERS, USER’S INDEMNIFICATION OBLIGATIONS, USER’S DUTY TO MITIGATE DAMAGES, THE LAW GOVERNING THE PAYROLL AGREEMENT, AND DISPUTE RESOLUTION PROCEDURES THEREUNDER.
        
        <p><strong>2.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">AutomotoHR’s Provision of the Payroll Service Is Governed by the Payroll Agreement</span>.
        Subject to the terms and conditions of the Payroll Agreement, AutomotoHR agrees to use reasonable efforts to provide User with the Payroll Service in accordance with the Payroll Agreement.</p>
        <p><strong>3.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Obligations Under the AutomotoHR Terms</span>.
        In addition to the obligations specified in these Payroll Terms, User has certain obligations under the AutomotoHR Terms, including but not limited to obligations to (i) designate an Account Administrator; (ii) be responsible for actions taken under User’s Account; (iii) follow instructions that AutomotoHR provides to User with respect to the Payroll Service; (iv) provide accurate, timely, and complete information required for AutomotoHR to perform the Payroll Service and maintain the accuracy and completeness of such information; (v) notify AutomotoHR of third-party notices, such as Internal Revenue Service (“IRS”) penalty notices, which could affect AutomotoHR’s ability to effectively provide the Payroll Service or which could increase the likelihood that a Claim is brought against User or AutomotoHR in connection with the Payroll Service; and (vi) refrain from taking certain prohibited actions, as described in further detail in Section 8 (User Is Responsible for Certain Information and Obligations Relating to the Services) and Section 13 (General Prohibitions) of the AutomotoHR Terms. </p>
        <p><strong>4.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Payroll Service</span>. 
        Provided that User meets User’s payment obligations and complies with the terms of the Payroll Agreement, then as long as User is subscribed to the Payroll Service, AutomotoHR will provide User with the Payroll Service for the purposes of (i) calculating payroll and its associated liabilities for User’s business; (ii) processing payroll and making related payroll payments; (iii) making certain payroll tax payments and payroll tax filings electronically; and (iv) if applicable, sending wage garnishments, such as child support payments, to applicable local, state, or federal agencies. In performing the Payroll Service, including for each of the foregoing purposes, AutomotoHR will rely on the information furnished by User, User’s Account Administrators, or User’s Authorized Representatives, and AutomotoHR is not responsible or liable for any errors resulting from such reliance, as further described in Section 20 (Limitation of Liability) of the AutomotoHR Terms. User may not use the Payroll Service on a professional basis for anyone other than User, unless User is actively participating in a AutomotoHR accountant program, in which case User may use the Payroll Service in accordance with the terms of such program.    
    </p>
        <p>
        Depending on the type of Payroll Service User requests, User may need to agree to additional terms and conditions and complete and sign additional forms or authorizations that AutomotoHR provides to User, as required by law or as otherwise necessary to provide the Payroll Service.
            </p>
        <p>
Prior to User’s initial payroll processing date, User must submit the completed and executed documents AutomotoHR requires for providing the Payroll Service, including User’s payroll and bank account information, any required federal, state, or local powers of attorney, and any additional information requested by AutomotoHR. The Payroll Service provided will be based on and is dependent upon information provided to AutomotoHR by User (including proof of federal, state, and local tax identification numbers). Failure to provide the required documents may adversely impact AutomotoHR’s ability to perform the Payroll Service. User is also responsible for: (i) depositing any federal, state, and local withholding liabilities incurred prior to enrolling in the Payroll Service; (ii) submitting any payroll returns to tax agencies (state, federal, and/or local) that were due for payroll tax liabilities incurred prior to enrolling in the Payroll Service; and (iii) cancelling any prior payroll service or services of professional employee organizations/employee leasing companies.            Prior to User’s initial payroll processing date, User must submit the completed and executed documents AutomotoHR requires for providing the Payroll Service, including User’s payroll and bank account information, any required federal, state, or local powers of attorney, and any additional information requested by AutomotoHR. The Payroll Service provided will be based on and is dependent upon information provided to AutomotoHR by User (including proof of federal, state, and local tax identification numbers). Failure to provide the required documents may adversely impact AutomotoHR’s ability to perform the Payroll Service. User is also responsible for: (i) depositing any federal, state, and local withholding liabilities incurred prior to enrolling in the Payroll Service; (ii) submitting any payroll returns to tax agencies (state, federal, and/or local) that were due for payroll tax liabilities incurred prior to enrolling in the Payroll Service; and (iii) cancelling any prior payroll service or services of professional employee organizations/employee leasing companies.
        
        </p>
        <p>
        In performing the Payroll Service, User acknowledges and agrees that (i) AutomotoHR is not acting in a fiduciary capacity for User and/or User’s business; (ii) using the Payroll Service does not relieve User of User’s obligations under local, state, or federal laws or regulations to retain records relating to User’s data contained in AutomotoHR’s files; and (iii) any information that AutomotoHR provides in connection with the Payroll Service is for informational purposes only and should not be construed by User as legal, tax, or accounting advice.        
        </p>
        <p><strong>5.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Payroll Account</span>.
        
        An Account Administrator or Authorized Representative shall approve and submit the Payroll Information (as defined below), thereby authorizing AutomotoHR to create and transmit credit or debit entries (the “Entries”) necessary to process User’s payroll and payroll tax transactions.    
     </p>
        <p><strong>6.</strong> &nbsp;&nbsp;<span class="underline-text">Payroll Information</span>. 
        
        AutomotoHR will notify User via electronic communication or by other means when all information necessary to begin the Payroll Service has been received and the enrollment process for the Payroll Service has been completed. User shall then, prior to submitting User’s first payroll, review the Payroll Information for completeness and accuracy. For the purposes of the Payroll Agreement, “Payroll Information” shall mean any information provided to AutomotoHR in connection with the Payroll Service, including but not limited to information provided by User, Account Administrators, Authorized Representatives, User’s employees, or User’s independent contractors, and all information posted in connection with the Payroll Service for User’s review on the Platform or otherwise requested for review by AutomotoHR, such as the information used to calculate and pay employee payroll, track User’s defined employee benefits, pay payroll taxes to applicable taxing agencies (including User’s employer identification number(s), unemployment insurance tax rates, and employment tax deposit schedule), produce payroll tax returns and W-2 statements, and print checks on User’s Account (if applicable). User must correct or provide, respectively, any incorrect or missing Payroll Information, either through the Platform or by notifying AutomotoHR in the manner specified in the applicable electronic communication received by User and within the time period specified therein. User is fully responsible for the accuracy of all information User provides, submits, and/or approves (whether provided directly or through User’s Account Administrators or Authorized Representatives), and User is solely responsible for any Claims, including but not limited to IRS penalties and/or interest, and other penalties and/or interest arising from the failure to timely provide and maintain accurate and complete Payroll Information at all times.    
    </p>
        <p>
        User agrees that by submitting each payroll (including the first payroll): (i) User approves all Payroll Information; (ii) User represents and warrants to AutomotoHR that no Payroll Information submitted to AutomotoHR will result in Entries that would violate the sanctions program of the Office of Foreign Assets Control of the U.S. Department of the Treasury or any other applicable laws, rules, or regulations; (iii) User waives and releases any Claim against AutomotoHR arising out of any errors or omissions in the Payroll Information which User has not corrected (whether directly or through User’s Account Administrators or Authorized Representatives) or has not requested AutomotoHR to correct; and (iv) User acknowledges that any subsequent request for corrections will be considered special handling, and additional fees may be charged. Final responsibility for any audits or assessments rests with User. AutomotoHR will not have any responsibility for verifying the accuracy of any data User provides via the Platform or via any other method.        
        </p>
        <p>
            
        User acknowledges, agrees, and understands that (i) any information or instructions (including but not limited to Payroll Information and Entries) communicated to AutomotoHR by User, an Account Administrator, or an Authorized Representative (or anyone that AutomotoHR reasonably believes to be User, an Account Administrator, or an Authorized Representative) will be deemed fully authorized by User, and User shall be fully responsible for the accuracy of such information and instructions, and any Claims, including but not limited to any IRS penalties and/or interest or other penalties and/or interest arising therefrom; and (ii) notwithstanding such deemed authorization, AutomotoHR may in its sole discretion refuse to accept or act upon any such instructions.    
    </p>
        <p>
        AutomotoHR, its employees, and agents will only collect, use, and disclose data furnished by User or produced by AutomotoHR under this Agreement in accordance with AutomotoHR’s <a href="https://revamp.automotohr.com/privacy-policy" target="_blank" style="color: rgb(11, 118, 210);"> Privacy Policy</a>.
        </p>
        <p><strong>7.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Payroll Authorizations</span>. 
        
        AutomotoHR will use reasonable efforts to verify that anyone providing an instruction to approve, release, cancel, or amend the Payroll Information used to create Entries (each, a “Payment Order”) to be originated by AutomotoHR is either User, an Account Administrator, or an Authorized Representative. AutomotoHR does not verify or review Payment Orders for the purpose of detecting any errors; it is User’s responsibility to verify the accuracy of Payment Orders. User will be bound by any Payment Order that is received by AutomotoHR in compliance with this designated authorization procedure, and User shall indemnify and hold AutomotoHR and the other Indemnified Parties harmless from and against any Claims arising from the execution of a Payment Order in good faith and in compliance with such procedures.    
    </p>
        <p>
        If a Payment Order describes the payee inconsistently by name and account number, (i) payment may be made on the basis of the account number even if User identifies a person different from the named payee; or (ii) AutomotoHR may, in its sole discretion, refuse to accept or may return the Payment Order. If a Payment Order describes a participating financial institution inconsistently by name and identification number, the identification number may be relied upon as the proper identification of the financial institution. If a Payment Order identifies a non-existent or unidentifiable person or account as the payee or the payee’s account, AutomotoHR may, in its sole discretion, refuse to accept or may return the Payment Order.        
        </p>
        <p><strong>8.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Bank Account Debiting and Crediting</span>.
        On or prior to User’s payroll direct deposit and/or payroll tax deposit date or other applicable settlement or due date, User authorizes AutomotoHR to initiate debit Entries to the Bank Account at the depository financial institution indicated by the routing number associated with the Bank Account that User provides to AutomotoHR (the “Bank”), and to debit the Bank Account in such amounts as are necessary to (i) fund User’s direct deposits; (ii) pay any fees or charges associated with the Payroll Service, including, without limitation, finance charges; (iii) pay User’s payroll taxes; (iv) pay any debit, correcting, or reversing Entry initiated pursuant to the Payroll Agreement which is later returned to AutomotoHR; (v) verify the Bank Account through a test deposit or debit authorization; and (vi) pay any other amount that is owing under the Payroll Agreement or in connection with the Payroll Service. User also authorizes AutomotoHR to initiate credit Entries to the Bank Account in the event that AutomotoHR is required to return Unpaid Funds to User, as described in Section 15 of these Payroll Terms. These authorizations are to remain in full force and effect until AutomotoHR has received written notice from User of termination of any such authorizations in such time and such manner as to afford AutomotoHR and the Bank a reasonable opportunity to act upon such notice. AutomotoHR is not responsible for determining whether the bank accounts of any payors or payees have deposit or withdrawal restrictions.        
        </p>
        <p>
        User acknowledges that the origination of Automated Clearing House (“ACH”) transactions to the Payroll Account (as defined below) and the transmission of funds via ACH transactions to the payee’s account must comply with applicable laws, rules, and regulations, including the NACHA Rules and Article 4A of the Uniform Commercial Code, as adopted in California and as may be amended from time to time (as amended, the “UCC”).        
        </p>
        <p><strong>9.</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Requirements for Bank Account Funds</span>. 
        
        User will maintain in the Bank Account, as of the applicable payroll direct deposit date, payroll tax deposit date, or other settlement or due date and time, immediately available funds sufficient to cover all disbursements, fees, payroll taxes or any other amounts due (collectively, the “Amounts Due”) under the Payroll Agreement. User’s obligation to have sufficient funds in the Bank Account to cover the Amounts Due matures at the time AutomotoHR originates the applicable Entries for the Amounts Due and is unaffected by termination of the Payroll Service. AutomotoHR may set off any amounts User owes to it against any amounts it owes to User in order for AutomotoHR to obtain payment of User’s obligations as set forth in the Payroll Agreement.    
    </p>
        <p>
        If User does not have sufficient funds in the Bank Account to pay the Amounts Due at the time required, or if User refuses to pay the Amounts Due, then AutomotoHR will not be able to pay out the Amounts Due to the applicable parties and will not be liable for any consequences or Claims directly or indirectly arising from such failure to pay, and AutomotoHR may (i) debit the Bank Account or any other account owned in whole or in part by User to pay disbursements, fees or charges, payroll taxes, or other amounts due; (ii) refuse to pay any unremitted payroll taxes to the applicable tax agencies, in which case the payroll tax liability will become User’s sole responsibility; (iii) refuse to perform further Services; and/or (iv) immediately terminate the Payroll Agreement. For any amounts due and unpaid, AutomotoHR may assess finance charges on such amounts and recover certain fees and costs of collection associated with such amounts in accordance with Section 2 (Services Fees and Charges) of the AutomotoHR Terms.        
        </p>
        <p><strong>10</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Certain User Agreements and Acknowledgments</span>. Amounts withdrawn from the Bank Account for payroll direct deposits and payroll taxes (“Payroll Funds”) will be held by AutomotoHR in accounts at AutomotoHR’s financial institutions (collectively, the “Payroll Account”) until such time as those payments are due to User’s employees and/or independent contractors and the appropriate taxing agencies, and no interest will be paid to User on these amounts. User acknowledges that AutomotoHR is entitled to invest the Payroll Funds in accordance with its investment guidelines established from time to time, and that AutomotoHR, in its own capacity, is entitled to all income and gains derived from or realized from such investments and is not accountable to User, User’s employees, or any other person for such income or gains. In order to facilitate the timely payment of payroll direct deposits and payroll taxes, AutomotoHR may pledge any investments held in the Payroll Account in connection with a loan, rather than convert such investments to cash for each tax payment. To the extent AutomotoHR receives the Payroll Funds, AutomotoHR shall indemnify and hold User harmless from and against any loss of any portion of the principal amount of the Payroll Funds (including any losses of principal resulting from the investment of the Payroll Funds) caused by AutomotoHR while holding the funds in its Payroll Account. If AutomotoHR incurs losses on the investment of the Payroll Funds or uses the Payroll Funds for any other purpose, AutomotoHR will make the required payroll direct deposits and payroll tax deposits on User’s behalf by using AutomotoHR’s own funds or other assets. User acknowledges that no state or federal agency monitors or assumes any responsibility for AutomotoHR’s financial solvency.</p>
        <p>
        Amounts withdrawn from the Bank Account for payroll direct deposits and payroll taxes (“Payroll Funds”) will be held by AutomotoHR in accounts at AutomotoHR’s financial institutions (collectively, the “Payroll Account”) until such time as those payments are due to User’s employees and/or independent contractors and the appropriate taxing agencies, and no interest will be paid to User on these amounts. User acknowledges that AutomotoHR is entitled to invest the Payroll Funds in accordance with its investment guidelines established from time to time, and that AutomotoHR, in its own capacity, is entitled to all income and gains derived from or realized from such investments and is not accountable to User, User’s employees, or any other person for such income or gains. In order to facilitate the timely payment of payroll direct deposits and payroll taxes, AutomotoHR may pledge any investments held in the Payroll Account in connection with a loan, rather than convert such investments to cash for each tax payment. To the extent AutomotoHR receives the Payroll Funds, AutomotoHR shall indemnify and hold User harmless from and against any loss of any portion of the principal amount of the Payroll Funds (including any losses of principal resulting from the investment of the Payroll Funds) caused by AutomotoHR while holding the funds in its Payroll Account. If AutomotoHR incurs losses on the investment of the Payroll Funds or uses the Payroll Funds for any other purpose, AutomotoHR will make the required payroll direct deposits and payroll tax deposits on User’s behalf by using AutomotoHR’s own funds or other assets. User acknowledges that no state or federal agency monitors or assumes any responsibility for AutomotoHR’s financial solvency.        
        </p>
        <p>
        AutomotoHR calculates applicable payroll taxes in accordance with state requirements; however, due to differences in computational methods (e.g., rounding), it is possible that AutomotoHR’s computation of User’s applicable taxes may deviate in a fractional manner from the amount charged by an applicable taxing authority (typically a difference of less than $0.10 per taxing authority per payroll). Sometimes, this will result in AutomotoHR withdrawing slightly less than what ultimately is required to be remitted to the applicable taxing authority. In this case, User agrees that AutomotoHR’s computation is correct, but AutomotoHR will cover the difference on User’s behalf and will not seek additional funds from User. Sometimes, this will result in AutomotoHR withdrawing slightly more than what ultimately is required to be remitted to the applicable taxing authority. In this case, User agrees that AutomotoHR’s computation is correct, and that User is not entitled to a refund of or credit for the excess funds.        
        </p>
<p>
In the event that AutomotoHR erroneously credits an amount to the Bank Account in excess of the amount that should have been credited (the “Excess Credit Amount”), if any, then User shall promptly notify AutomotoHR as soon as it becomes aware of such erroneous credit. User authorizes AutomotoHR to debit any Excess Credit Amounts from the Bank Account, and if the Bank Account contains insufficient funds to cover the Excess Credit Amount, User agrees to promptly refund the Excess Credit Amount to AutomotoHR through other payment methods that AutomotoHR may deem acceptable at its sole discretion.

</p>

        <p><strong>11</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">ACH Origination</span>.
        
        The Payroll Service will enable User to enter the Payroll Information and to approve and submit it to AutomotoHR for creation, formatting, and transmission of Entries in accordance with the NACHA Rules and the UCC. AutomotoHR may reject any Payroll Information or Entry which does not comply with the requirements in the Payroll Agreement, NACHA Rules, or the UCC, or with respect to which the Bank Account does not contain sufficient available funds to pay for the Entry. If any Payroll Information or Entry is rejected, AutomotoHR will make a reasonable effort to notify User promptly so that User may correct such Payroll Information or request that AutomotoHR correct the Entry and resubmit it. A notice of rejection of Payroll Information or an Entry (each, a “Rejection Notice”) will be effective when given and may be delivered through any means, including via email or through User's Account. AutomotoHR will have no liability to User for (i) the rejection of any Payroll Information or Entry or any Claims directly or indirectly arising therefrom; or (ii) any delay in providing, or any failure to provide, User with a Rejection Notice, or any Claims arising directly or indirectly therefrom. If User requests that AutomotoHR correct any Payroll Information or Entries on User's behalf, AutomotoHR may attempt to do so; provided, however, that AutomotoHR is not obligated to make any requested correction, and AutomotoHR is not liable for any Claims or other consequences that may directly or indirectly result from AutomotoHR’s attempt to correct, or failure to correct, such Payroll Information or Entries.    
    </p>
        <p>
        After the Payroll Information has been approved by an Account Administrator and submitted to AutomotoHR for the purposes of initiating a payroll-related transaction (such action, to “Submit,” and Payroll Information that has been submitted in the foregoing manner, “Submitted Payroll Information”) and received by AutomotoHR, User may not be able to cancel or amend such Submitted Payroll Information. AutomotoHR will use reasonable efforts to act on any cancellation or amendment requests it receives from an Account Administrator prior to transmitting the Entries to the ACH or gateway operator, but will have no liability if the cancellation or amendment is not effected. User will reimburse AutomotoHR for any expenses, losses, fines, penalties, or damages AutomotoHR may incur in effecting or attempting to effect such a request. Except for Entries created from Payroll Information that has been re-approved and re-Submitted by an Account Administrator in accordance with the requirements of the Payroll Agreement, AutomotoHR will have no obligation to retransmit a returned Entry to the ACH or gateway operator if AutomotoHR complied with the terms of the Payroll Agreement with respect to the original Entry.        
        </p>
       
       
    </div>
    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">

    <p><strong>12</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Payroll Processing Schedule</span>. 
        
        AutomotoHR will process the Submitted Payroll Information and Entries in accordance with AutomotoHR’s then-current processing schedule applicable to User, provided that (i) the Submitted Payroll Information is received by AutomotoHR no later than User's applicable cut-off time for Submitted Payroll Information on a business day; and (ii) the ACH is open for business on that business day. If AutomotoHR receives approved and Submitted Payroll Information after the applicable cut-off time for Submitted Payroll Information on a given business day, or if AutomotoHR receives the Submitted Payroll Information on a non-business day, AutomotoHR will not be responsible for failure to process the Submitted Payroll Information on that day. If any of the requirements of clauses (i) or (ii) of this paragraph are not satisfied, AutomotoHR will use reasonable efforts to process the Submitted Payroll Information and transmit the Entries to the ACH with the next regularly-scheduled file created by AutomotoHR (which will only occur on a business day on which the ACH is open for business).
        </p>

        <p>
        AutomotoHR’s standard processing time for payroll and contractor payments is four (4) business days, but if User qualifies for one of AutomotoHR’s expedited payroll processing programs (each, an “Expedited Payroll Program”), then subject to the provisions of this paragraph, and subject to an Account Administrator approving and Submitting Payroll Information to AutomotoHR, AutomotoHR will process User’s payroll and contractor payments in less than four (4) business days. Whether User initially qualifies for or continues to qualify for AutomotoHR’s Expedited Payroll Programs is at the sole discretion of AutomotoHR, and AutomotoHR has no obligation to provide expedited payroll processing services to User. If AutomotoHR processes User’s payroll and/or contractor payments through an Expedited Payroll Program and the Bank Account has insufficient funds to cover such Amounts Due for such payroll and/or contractor payments, or the Bank otherwise rejects the portions of the ACH files originated by AutomotoHR that relate to Entries for such Amounts Due, then User will owe, and be liable to AutomotoHR for, such Amounts Due (the “Expedited Payroll Amounts Due”). User will ensure that any Expedited Payroll Amounts Due are promptly paid to AutomotoHR via a payment method that AutomotoHR, in its sole discretion, determines is acceptable. If User is liable for any Expedited Payroll Amounts Due or if AutomotoHR has any reason to believe that User may be in violation of the Payroll Agreement, then AutomotoHR may immediately revoke User’s eligibility for any Expedited Payroll Program. This provision shall not limit AutomotoHR from exercising any other rights or remedies it may have under the Payroll Agreement to recover the Expedited Payroll Amounts Due.        </p>



        <p><strong>13</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">ACH Transactions and Entries</span>.
        
        Origination, receipt, return, adjustment, correction, cancellation, amendment, and transmission of Entries must be in accordance with the NACHA Rules, and, with respect to credit Entries which constitute Payment Orders, the UCC, as both are varied by this Agreement. User acknowledges that User has had an opportunity to review, and agrees to comply with, and be bound by, the NACHA Rules and the UCC.    
    </p>
        <p>
        Credit given by AutomotoHR to User with respect to an ACH credit Entry is provisional until AutomotoHR receives final settlement for such Entry through a Federal Reserve Bank. If AutomotoHR does not receive such final settlement, User is hereby notified and agrees that AutomotoHR is entitled to a refund from User in the amount credited to User in connection with such Entry, and the party making payment to User via such Entry (i.e., the Originator (as defined in the NACHA Rules) of the Entry) shall not be deemed to have paid User in the amount of such Entry.        
        </p>
        <p>
        Upon User’s request, AutomotoHR will make a reasonable effort to reverse an Entry, but will have no responsibility for the failure of any other person or entity to honor User's request, and AutomotoHR cannot guarantee that the Entry will be successfully reversed. User agrees to reimburse AutomotoHR for any costs or expenses incurred in attempting to honor such a reversal request. If required under the NACHA Rules or the UCC, User must obtain a payee’s consent before attempting to reverse an Entry that was credited to such payee. By initiating a request to reverse an Entry that was credited to a payee, User represents and warrants to AutomotoHR that it has already obtained the payee’s consent for the reversal, if such consent is required under the NACHA Rules or the UCC.        
        </p>
        <p>
        Under the NACHA Rules, which are applicable to ACH transactions involving User’s Account, AutomotoHR is not required to give next day notice to User of receipt of an ACH item and AutomotoHR will not do so. However, AutomotoHR will continue to inform User of the receipt of payments in the periodic Bank Account transaction history report that AutomotoHR makes available to User in User’s Account. User acknowledges and understands that while User may not be notified via email of every Bank Account transaction initiated by AutomotoHR in connection with the Payroll Service, User may view its Bank Account transaction information in User’s Account.        
        </p>
        <p>
User expressly acknowledges that AutomotoHR does not intentionally or knowingly engage in or support International ACH Transactions (“IATs”), as defined in the NACHA Rules. User represents and warrants that (i) the direct funding for the Entries originated by AutomotoHR on behalf of User does not come from or involve a financial agency office that is located outside the territorial jurisdiction of the United States; (ii) User will not instruct AutomotoHR to create, originate, or transmit Entries that use IAT as the Standard Entry Class Code (as defined in the NACHA Rules), or are otherwise required to be IATs under the NACHA Rules; and (iii) User will not engage in any act or omission that causes or results in AutomotoHR creating, originating, or transmitting an IAT or a payment that should have been categorized as an IAT pursuant to the NACHA Rules. AutomotoHR may, in its sole discretion, temporarily or permanently suspend providing the Payroll Service to User, without liability, if AutomotoHR has reason to believe that User has breached any of the foregoing representations and warranties in this paragraph. User acknowledges that User is the Originator (as defined in the NACHA Rules) of each Entry and assumes the responsibilities of an Originator under the NACHA Rules. User further acknowledges that under the NACHA Rules and the UCC, AutomotoHR, as a Third-Party Sender (as defined in the NACHA Rules), is required to make certain warranties on behalf of the Originator with respect to each Entry. User agrees to indemnify AutomotoHR for any Claim which results, directly or indirectly, from a breach of such a warranty made by AutomotoHR on behalf of User, unless such breach results solely from AutomotoHR’s own gross negligence or intentional misconduct. User also acknowledges that under the NACHA Rules and the UCC, AutomotoHR is required to indemnify certain persons, including, without limitation, the ODFI (as defined in the NACHA Rules), for the Originator’s failure to perform its obligations thereunder. User agrees to indemnify AutomotoHR for any Claims which result from the enforcement of such an indemnity, unless the enforcement results solely from AutomotoHR’s own gross negligence or intentional misconduct.        
        </p>
        <p><strong>14</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Taxes; Liability</span>. 
        In order to use the Payroll Service, User must submit accurate wage and payroll information to AutomotoHR during and after the enrollment process. AutomotoHR will not be liable for any penalty, interest, or other Claim that results from inaccurate or incomplete information that User, an Account Administrator, or an Authorized Representative supplies. AutomotoHR shall only file tax returns on User's behalf once User has processed User's payroll through the Platform and the payroll has been paid out to the payees. User shall timely and accurately update all wage and payroll information as necessary to reflect changes and respond with additional information, as may be requested from time to time by AutomotoHR. It is User's responsibility to submit complete, timely, and accurate information to AutomotoHR in connection with the Payroll Service. Any penalty or interest incurred, or any other Claim that arises, due to inaccurate or incomplete information provided by User will be User's sole responsibility. User further agrees to hold AutomotoHR harmless from such liability. AutomotoHR, at its option, may decide not to file User's payroll tax returns, pay User's payroll taxes, or otherwise process User's payroll if there are any unresolved problems with any information requested by AutomotoHR or submitted by User, an Account Administrator, or an Authorized Representative. AutomotoHR’s sole liability and User's sole remedy for AutomotoHR’s negligent failure to perform the payroll tax portion of the Payroll Service shall be as follows: (i) AutomotoHR will remit the payroll taxes received from User to the appropriate taxing authority; and (ii) AutomotoHR will reimburse User or pay directly to the appropriate taxing authority any penalties resulting from such negligent error or omission by AutomotoHR, provided that User must use reasonable efforts to mitigate any penalties or losses resulting from such negligent error or omission by AutomotoHR.    
    </p>
        <p>
        Important Tax Information: Even though User has authorized a third party, such as AutomotoHR, to file payroll tax returns and make payroll tax payments, ultimately, User is held responsible by taxing authorities for the timely filing of employment tax returns and the timely payment of employment taxes for User’s employees. AutomotoHR and the IRS recommend that User enroll in the U.S. Treasury Department’s Electronic Federal Tax Payment System (“EFTPS”), to monitor User’s IRS account and ensure that timely tax payments are being made for User. User may enroll in the EFTPS online at www.eftps.gov, or by calling (800) 555-4477 for an enrollment form. State tax authorities generally offer similar means to verify tax payments. User should contact the appropriate state offices directly for details.        
        </p>


        <p><strong>15</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Failed Direct Deposits</span>. 
        In the event that a direct deposit payroll payment fails to be paid to the payee and AutomotoHR cannot ultimately successfully make a payment on User's behalf to the payee, and the funds are returned to AutomotoHR (“Unpaid Funds”), AutomotoHR will notify User of such Unpaid Funds and provide User with the appropriate details related to those funds. In addition, AutomotoHR will return the Unpaid Funds to User in accordance with Section 8 of these Payroll Terms. User, not AutomotoHR, is required to contact payees and/or otherwise resolve the Unpaid Funds. User acknowledges that User is responsible for complying with all applicable state unclaimed or abandoned property laws related to Unpaid Funds, and User hereby expressly releases AutomotoHR from all liability and Claims directly or indirectly arising from state unclaimed or abandoned property laws, including any applicable penalties and/or interest. AutomotoHR shall have no obligation to defend or otherwise indemnify User in the event of an audit, examination, assessment, or other enforcement action by a state related to the Unpaid Funds under its unclaimed or abandoned property laws. User may update the required wage and payroll information as necessary to reflect any necessary changes in accordance with the provisions of these Payroll Terms to allow AutomotoHR to re-perform the direct deposit payroll payment on User's behalf.    </p>


        <p><strong>16</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Effect of Termination of the Payroll Service</span>.
        
        User acknowledges and understands that if User terminates the Payroll Service through User’s Account or AutomotoHR terminates the Payroll Service pursuant to Section 22 (Term; Termination; Suspension) of the AutomotoHR Terms, then such termination may not be reversible. In the event that User or AutomotoHR terminates User’s Payroll Service, then as of the time of such termination, AutomotoHR will have no obligation to make further payroll tax filings on User’s behalf. Notwithstanding the foregoing, if User or AutomotoHR terminates the Payroll Service, User will be asked to make specific elections regarding whether it would like AutomotoHR to make certain final payroll tax filings (such filings, the “Final Payroll Tax Filings”) on User’s behalf following such termination of the Payroll Service (such elections, the “Post-Termination Filing Elections”). If User does not provide AutomotoHR with its Post-Termination Filing Elections promptly following termination of the Payroll Service, then User authorizes AutomotoHR to make the Post-Termination Filing Elections for User on User’s behalf (the “AutomotoHR Selections”). User acknowledges and agrees that AutomotoHR may rely on User’s Post-Termination Filing Elections and the AutomotoHR Selections, and AutomotoHR is not responsible or liable for (i) any consequences or Claims arising (directly or indirectly) from such reliance; or (ii) any Resulting Errors, or any consequences or Claims arising (directly or indirectly) from any Resulting Errors, in the Final Payroll Tax Filings.    
    </p>
        <p><strong>17</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Consent to Share Certain Employee and Independent Contractor Information with Employer</span>. 
        
        User acknowledges and understands that in providing the Payroll Service, AutomotoHR acts as an intermediary between employers and their employees and/or independent contractors. If User is an employee or independent contractor, then User hereby authorizes AutomotoHR to share with User’s employer any information that User has provided to AutomotoHR in connection with the Payroll Service.    </p>


        <p><strong>18</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Fees</span>. </p>
        <p><span class="underline-text">18.1 Fees.</span>
            Fees are as provided in applicable Service Order(s) and are based on the number of Users, the Services ordered, applicable flat rates, the subscription term and other costs or charges.
        </p>
        <p><span class="underline-text">18.2 Increase in Number of Users.</span>
            If at any point during your then-current subscription term you have a User Increase, you will be charged for the increased number of Users, prorated for the balance of the applicable subscription term, at the price for that subscription term or as agreed to in the applicable Service Order.
        </p>
        <p><span class="underline-text">18.3 Decrease in the Number of Users.</span>
            If the number of Users decreases during your then-current subscription term, you will not be entitled to any refunds, credits or adjustment of the Fees already paid or owed for the remainder of the committed subscription term, except as required by applicable law.
        </p>

        <p><span class="underline-text">18.4 Upgrade to Higher Priced Options.</span>
            If during your then-current subscription term you choose to Upgrade, you will be billed for the difference between the two pricing options, prorated for the balance of such subscription term, at our then list price or as agreed to in the applicable Service Order.
        </p>
        <p><span class="underline-text">18.5 New or Additional Service Offerings.</span>
            If we release new offerings and you choose to subscribe to such offering(s) during a then-current subscription term, you will be billed for such product(s) at our then list price, prorated for the balance of your subscription term or as agreed to in the applicable Service Order. Similarly, if you wish to add additional products to the Services you are subscribed to, you will be billed for such product(s) at our then list price, prorated for the balance of your subscription term or as agreed to in the applicable Service Order.
        </p>

        <p><span class="underline-text">18.6 Downgrade to Lower Priced Options.</span>
            If you wish to downgrade your subscription to a lower priced option prior to the end of the then-current subscription term, you will not be entitled to a refund, credit or price adjustment for any portion of the Fees already paid or owed for the remainder of the committed subscription term, except as required by applicable law. You may downgrade to lower priced options for an upcoming renewal term if any such options are available for subscription and if you give us notice prior to the renewal term as set forth in Section 12.9 (Renewal Subscriptions Fees).
        </p>
        <p><span class="underline-text">18.7 Transactional Fees.</span>
            We reserve the right to charge certain Fees based on specific transactions or requests made through the Services (such as for background checks, OFAC checks, data export requests, document copy requests, etc.). Such Fees will be as set forth in the applicable Service Order or in the Services.
        </p>

        <p><span class="underline-text">18.8 Promotional Fees.</span>
            We reserve the right to offer certain promotional rates from time to time, which may be offered solely on a one-time basis, and may apply solely to a specific subscription term or service. Any such promotional pricing is offered in our sole discretion, and we are under no obligation to offer any promotional pricing to you even if we have provided promotional pricing offers to any other customer, or to continue to offer any promotional pricing previously offered.
        </p>
        <p><span class="underline-text">18.9 Renewal Subscription Fees.</span>
            Unless otherwise agreed to in an applicable Service Order, the subscription Fees for renewal terms will be at our then-current list price. You agree that you are responsible for all applicable Fees, and that upon each such renewal term, your designated payment method will be automatically charged for all the monthly or annual Fees (as applicable) for the renewal subscription term on or around the Monthly Renewal Date or Annual Renewal Date, as applicable, without further authorization from you and/or without further notice by us (unless required by law). You may adjust your subscription for an upcoming renewal term if you give us notice 30 days prior to the expiration of your then-current annual subscription term or 30 days prior to the expiration of your then-current monthly subscription term that (i) you want to downgrade to then-available, lower priced options (i.e., provided any such products or Services are available for subscription) and/or that (ii) you want to decrease the number of Users; however, to decrease the number of Users, the quantity of Users in your organization or with required access to the Services must always equal the number of Users for whom Fees are applicable.
        </p>
        <p><span class="underline-text">18.10 Non-cancelable & Non-Refundable.</span>
            Except as stated in MSA, Services are not cancelable and Fees are not refundable.
        </p>

        <p><strong>19</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Payment Terms</span>. </p>
        <p><span class="underline-text">19.1 Payment.</span>
            Before you access or use the Services, you agree to pay all the Fees as identified in applicable Service Order(s). Unless otherwise provided in your Service Order, all Fees, other than transactional Fees, are due in advance on the Effective Date and after such date, the Fees are due in advance on each Monthly Renewal Date or Annual Renewal Date (as applicable). Transaction Fees, if any, are due in accordance with the applicable Service Order. All Fees are quoted in, and all payments must be made in, U.S. dollars. (Authorization of Recurring ACH Debit or credit card on file) you authorize us to automatically debit all applicable Fees, from the designated account, via ACH debit or credit card transaction on the due date. In the event of a User Increase or an Upgrade, the Fees applicable to such User Increase or Upgrade are due as of the User Increase date or Upgrade date.
        </p>

        <p><span class="underline-text">19.2 Late Payment.</span>
            Late payments will accrue interest of 1.5% per month or the greatest amount allowed by state law, whichever is lower. We may suspend or terminate this MSA, a Service Order, or access to and use of the Services for failure to pay Fees as they come due. Additionally, if Fees are not paid when due, you will pay us costs of collection, including reasonable attorneys’ fees and expenses actually incurred.
        </p>
        <p><span class="underline-text">19.3 Taxes.</span>
            All payments required by this MSA exclude sales, value-added, use, or other taxes and obligations, all of which you will be responsible for and will pay in full, except for taxes based on our net income. If we have the legal obligation to pay or collect taxes for which you are responsible (Taxes), you authorize us to automatically debit the applicable taxes, from the designated account, via ACH debit transaction on the due date, unless you provide us with a valid tax exemption certificate authorized by the appropriate taxing authority.
        </p>
        <p><strong>20</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Term, Automatic Renewal & Termination</span>. </p>
        <p><span class="underline-text">20.1 Term of the MSA.</span>
            The MSA Term starts on the Effective Date and continues until all the subscription terms for the Services purchased under all Service Orders have expired or are terminated in accordance with this MSA.
        </p>

        <p><span class="underline-text">20.2 Subscription Term & Start Date(s).</span>
            Unless otherwise provided in an applicable Service Order, your initial subscription term is 12 months. The Subscription Start Date of all initial subscription terms begin on the Effective Date of this MSA. Subscription Start Date(s) for renewal terms are on the applicable Monthly Renewal Date or Annual Renewal Date.
        </p>

        <p><span class="underline-text">20.3 Automatic Renewal.</span>
            Unless otherwise specified in an applicable Service Order, all subscription terms automatically renew as follows: a monthly subscription term will automatically renew for additional, successive 1 month increments on your Monthly Renewal Date, unless you inform us, or we inform you, of non-renewal at least 30 days prior to your Monthly Renewal Date. Annual or multi-year subscription terms will automatically renew for additional, successive 12 month increments on your Annual Renewal Date, unless you inform us, or we inform you, of non-renewal at least 90 days prior to your Annual Renewal Date.
        </p>
        <p><strong>21</strong> &nbsp;&nbsp;&nbsp;&nbsp;<span class="underline-text">Termination.</span>. </p>
        <p><span class="underline-text">21.1 For Material Breach.</span>
            Either party will have the right to terminate this MSA, including ASAs, or the applicable Service Order, upon written notice, if the other party materially breaches this MSA and fails to cure such breach within 30 days after receipt of such written notice. This 30-day cure period will not apply in the case of your failure to pay Fees as they become due.
        </p>
        <p><span class="underline-text">21.3 Restricted Businesses.</span>
            If at any time AutomotoHR determines, in its sole discretion, that your business is a Restricted Business, we may terminate your and your Users’ access to and use of the Services immediately with or without notice. You agree that AutomotoHR will not be liable to you for any such termination.
        </p>
        <p><span class="underline-text">21.4 Effect of Termination.</span>
            Upon the effective date of termination of this MSA for any reason: (i) your right to access or use the Services will terminate immediately; (ii) we will cease providing the Services and we will deactivate or delete your account, and all associated materials, including Provided Content and Hosted Content, subject to our obligation to work with you to exporting Hosted Content under Section 21.5 (Data Removal); (iii) any and all your payment obligations under this MSA will become due immediately; (iv) within 30 days from the effective date of this MSA’s termination, if a party provides written notice to the other requesting return of such party’s Confidential Information, the receiving party will destroy (evidenced by a certificate of destruction) or return the tangible embodiments of the requesting party’s Confidential Information in its possession and shall not retain any copies of such Confidential Information except as required to comply with any applicable legal or accounting record keeping requirement. All ASAs will terminate immediately upon termination of this MSA.
        </p>


    </div>
</div>
<br>